#pragma once

#include "audio/eax.h"

#include <cstdint>
#include <iterator>

namespace sea::reverb {

	// Reverb preset for each environment type, generated by `tools/gen_reverb_presets.py`. 
	// Indexed as ANAM - 1.
	inline constexpr eax::ReverbProperties kPresets[] = {
#include "reverb/presets.inc"
	};

	inline constexpr std::uint32_t kEnvironmentCount = static_cast<std::uint32_t>(std::size(kPresets));  // ANAM 1..30
	static_assert(kEnvironmentCount == 30);

}
